### ISSUE TITLE
Add import / export commands for Layouts

### ISSUE THREAD

**Issue by baizmandesign** [OnTheGoSystems/toolset-cli#6]
I've been in touch with @decodekult about adding import and export commands for Layouts. Via email he mentioned, "Layouts is probably more complex, as there is no initial CLI implementation for it, and it is considered a legacy plugin just in maintenance." With some guidance from Toolset staff, I'd like to add support for these commands, and this issue can be assigned to me.

**Comment by zaantar** [comment]
Let us know how we can help you here!

**Comment by baizmandesign** [comment]
@zaantar I'm waiting on guidance from @decodekult since he said he would be able to provide some hints after the views import and export code was added. Earlier today I emailed Juan because that time is now! 

But if you have any pointers, I am all ears. The larger outline of the task is unclear to me, though it seems to be the case I need to create a new top-level command for layouts: `wp layouts`. Is there code I should use as a model? Or methods, classes, or other API functions I should pay attention to?

**Comment by zaantar** [comment]
@baizmandesign, ok. This is what I have at the moment:

- you already know the `Bootstrap` class to register new commands
- [`ToolsetCommand`](https://github.com/OnTheGoSystems/toolset-cli/blob/master/application/Commands/ToolsetCommand.php) is the superclass to extend for the new Layouts command 
- Whenever you can, I would suggest making use of [`WpCli`](https://github.com/OnTheGoSystems/toolset-cli/blob/master/application/WpCli.php) (`$this->wp_cli()`) instead of relying on the `\WP_CLI` class or namespace directly. This will help make the code more testable, when we eventually begin adding proper unit tests for this repository. If you're missing a particular method in the `WpCli` class, don't hesitate to add it.
- If you use PHPCS, the repo is configured with [Toolset Coding Standards](https://github.com/OnTheGoSystems/toolset-coding-standards). But it's not a huge deal if you don't follow these closely.

**Comment by baizmandesign** [comment]
@zaantar Thanks for the pointers. I've drafted a working version of the export command for layouts, but one of the files in the ZIP archive (`ddl-settings.json`) isn't exporting correctly due to a call to `is_admin()` in the `run` method of the `WPDDL_Options` class (located on line 42 in `layouts/classes-auto/wpddl-options.class.php`). The conditional is failing because WP CLI isn't requesting an administrative webpage. Can the offending conditional either be removed or modified per below?

```
private function run(){
    if ( is_admin() || WP_CLI ) {
        ...
    }
}
```

![Screen Shot 2021-01-14 at 22 58 03](https://user-images.githubusercontent.com/64377184/104679609-0bfe7d00-56bc-11eb-8792-cac0a8d66be8.png)

**Comment by zaantar** [comment]
@baizmandesign Great! Checking for `WP_CLI` won't be a problem. Let's see if we can squeeze this into the upcoming release.

**Comment by baizmandesign** [comment]
@zaantar Excellent news! Will you inform me when that's done? There's little point in committing the code related to the export command without it.

**Comment by zaantar** [comment]
@baizmandesign sure, I'll let you know!

**Comment by baizmandesign** [comment]
@zaantar I just spotted an error in the code snippet above to detect the presence of the WP_CLI constant. It ought to be as follows:

```
private function run(){
    if ( is_admin() || defined('WP_CLI') ) {
        ...
    }
}
```

**Comment by zaantar** [comment]
@baizmandesign thanks & no worries, I noticed that as well. But I am afraid that my merge request didn't make it into Layouts before it was tagged, so the next update _will not_ contain this fix yet, unless something unexpected happens. It should be included in a following release, though.

**Comment by baizmandesign** [comment]
@zaantar Yesterday I drafted a working version of the corresponding import command. It required making a few changes to `layouts/inc/theme/wpddl.theme-support.class.php`. [I've shared a patch to the code via gist here.](https://gist.github.com/baizmandesign/8d56f459f02ed4842402142449db13ae)

Once that's applied to the Layouts plugin, I can submit a PR for this issue with working code.

**Comment by zaantar** [comment]
This should start working with the next version of Layouts, 2.6.9.

**Comment by baizmandesign** [comment]
Awesome! Thanks, @zaantar!
